default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: db/themis_development

profile:
  <<: *default
  database: db/themis_development

test:
  <<: *default
  database: db/themis_test

production:
  <<: *default
  database: db/themis_production
